"""empty message

Revision ID: e2f0bd2e6a37
Revises: 
Create Date: 2020-10-09 22:00:58.041172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f0bd2e6a37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_en', sa.String(), nullable=True),
    sa.Column('category_ru', sa.String(), nullable=True),
    sa.Column('category_he', sa.String(), nullable=True),
    sa.Column('category_img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('users',
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('users_name', sa.String(length=80), nullable=True),
    sa.Column('users_email', sa.String(), nullable=False),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('unique_id'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_table('shop_items',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('header_en', sa.String(), nullable=True),
    sa.Column('header_ru', sa.String(), nullable=True),
    sa.Column('header_he', sa.String(), nullable=True),
    sa.Column('text_en', sa.String(), nullable=True),
    sa.Column('text_ru', sa.String(), nullable=True),
    sa.Column('text_he', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('min', sa.Integer(), nullable=True),
    sa.Column('max', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_items')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
